server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  beans:
    cache:
      time-to-live: 10s

amazon:
  dynamodb:
    region: eu-west-2
    endpoint: ${DYNAMO_ENDPOINT:http://localhost:8000/}
    table: ${DYNAMO_TABLE:Table}
    accesskey: ${DYNAMO_ACCESS_KEY:DYNAMO_ACCESS_KEY}
    secretkey: ${DYNAMO_SECRET_KEY:DYNAMO_SECRET_KEY}